### ISSUE TITLE
Issues with umlauts

### ISSUE THREAD

**Issue by pgtaboada** [cloudbees/zendesk-java-client#10]
Hi there, not sure where to start looking at. When I add any name or alias with umlauts, like "Peter Müller", I get an Unprocessable Entity Exception.

**Comment by johnou** [comment]
@pgtaboada can you provide some code to reproduce it?

**Comment by johnou** [comment]
@pgtaboada if you are alive please reopen this issue and provide a sample usage of the client that produces the Unprocessable Entity Exception.
