### ISSUE TITLE
Please cut a new release

### ISSUE THREAD

**Issue by kflorence** [cloudbees/zendesk-java-client#156]
Last release was Jun 20th.

**Comment by kflorence** [comment]
ping @stephenc @johnou @aheritier @ydubreuil

**Comment by stephenc** [comment]
@johnou @aheritier @ydubreuil WDYT? are we ready for a release?

**Comment by ydubreuil** [comment]
That it's time! I'm currently doing it actually

**Comment by ydubreuil** [comment]
Um, I forgot the fact that I don't have the rights to upload it :( I let you cut it @stephenc

**Comment by johnou** [comment]
@stephenc sgtm, the project I wrote which uses zendesk-java-client has gone into maintenance mode and has been pretty solid but I am happy to continue helping out with this library where I can.

**Comment by johnou** [comment]
@stephenc little nit from me, could you edit the description of the repo? it still has the capital D.. ZenDesk.

![nit](https://cloud.githubusercontent.com/assets/323497/20388669/3c025d40-acc6-11e6-81d6-b812f5f9a4b5.png)

**Comment by stephenc** [comment]
0.5.2

**Comment by kflorence** [comment]
Thanks all!
