### ISSUE TITLE
Add support for the is_public attribute of Ticket

### ISSUE THREAD

**Issue by davidwebster48** [cloudbees/zendesk-java-client#191]
Tickets have an attribute "is_public" (as per https://developer.zendesk.com/rest_api/docs/core/tickets#json-format).

I can't find any way to set this attribute via this client.

I will try to add support for this and if I get it working I'll submit a pull request.

**Comment by davidwebster48** [comment]
PR submitted: https://github.com/cloudbees/zendesk-java-client/pull/192

**Comment by duemir** [comment]
Closing since the PR was integrated since 0.5.5
