### ISSUE TITLE
ZendeskResponseException does not include body in the stack trace message

### ISSUE THREAD

**Issue by Helmsdown** [cloudbees/zendesk-java-client#207]
Can we include the response body in the message that gets passed to the super constructor

Instead of:
```java
 public ZendeskResponseException(int statusCode, String statusText, String body) {
        super(MessageFormat.format("HTTP/{0}: {1}", statusCode, statusText));
```

Do this:
```java
 public ZendeskResponseException(int statusCode, String statusText, String body) {
        super(MessageFormat.format("HTTP/{0}: {1} - {2}", statusCode, statusText, body));
```

My reasoning:
In my app my runtime exception bubble up to a common level and get logged (stacktrace plus other context that is stored in a thread local). When you log the stack trace of a ZendeskResponseException you do not see the response body, which has the really useful information. 

For example:
```
org.zendesk.client.v2.ZendeskResponseException: HTTP/422: Unprocessable Entity
	at org.zendesk.client.v2.Zendesk.complete(Zendesk.java:2130)
	at org.zendesk.client.v2.Zendesk.createOrganization(Zendesk.java:1028)
```

This does not tell you *why* the entity failed to process and thus is about as useless as a glass hammer.

**Comment by johnou** [comment]
@Helmsdown thanks!
