### ISSUE TITLE
Release version 0.6.0

### ISSUE THREAD

**Issue by aheritier** [cloudbees/zendesk-java-client#217]
We integrated various changes (some of them breaking the APIs thus let's release a 0.6.0 ?
Maybe just merge #176 , #216 and we fix #213

@johnou @stephenc WDYT ?

**Comment by aheritier** [comment]
For PR #190 I don't know

**Comment by johnou** [comment]
sounds good to me, to be honest I don't really see any benefits to #190.. models should ideally be populated from the API and boolean values are true or false unless they are optional in which case object Boolean would make sense.

**Comment by aheritier** [comment]
I agree @johnou I don't know if they could send sometimes an empty/null value for an boolean field (I just hope no)

**Comment by stephenc** [comment]
I think we should release... I don’t have a test environment still... so @aheriter can release ;-)

**Comment by stephenc** [comment]
Damn phone @aheritier

**Comment by aheritier** [comment]
Release done. Will be available in central in few hours @stephenc @johnou 
The badge on the homepage will let you know : https://github.com/cloudbees/zendesk-java-client
