### ISSUE TITLE
Update of simple custom fields is broken

### ISSUE THREAD

**Issue by aheritier** [cloudbees/zendesk-java-client#228]
Due to the change done in #210 to support multi-select fields the update of others custom fields does nothing (but it doesn't fail 🤷‍♂️ )

**Comment by johnou** [comment]
@aheritier ouch, guess it's the same bug for Action? :man_facepalming:

**Comment by aheritier** [comment]
yes @johnou :(

**Comment by johnou** [comment]
@aheritier well, the good news is that it wasn't a regression, Action only had a custom DE-serializer, not serializer.
