### ISSUE TITLE
Zendesk.getTicketsByStatus ignores status passed in

### ISSUE THREAD

**Issue by alexargo** [cloudbees/zendesk-java-client#23]
Was trying to get only my open tickets by calling Zendesk.getTicketsByStatus(Status.NEW); but I was getting ALL tickets. Zendesk.getTicketsFromSearch("status:open") did seem to work properly.

**Comment by johnou** [comment]
The latter is the correct usage, Zendesk.getTicketsByStatus(Status.NEW); transforms to Zendesk.getTicketsByStatus("new"); optionally you could write it like

{code}
Zendesk.getTicketsByStatus("status:" + Status.OPEN);
{code}

**Comment by johnou** [comment]
Sadly it looks like the end point Zendesk.getTicketsByStatus uses no longer supports pulling tickets by status..? https://developer.zendesk.com/rest_api/docs/core/tickets#getting-tickets

**Comment by tadrian** [comment]
I just did a search and got back only open tickets.  (not closed)
Zendesk.getTicketsFromSearch("status:open")

**Comment by aheritier** [comment]
Marked as deprecated
