### ISSUE TITLE
Zendesk client keeps the thread occupied even after performing Zendesk.close()

### ISSUE THREAD

**Issue by ujjwalsubedi** [cloudbees/zendesk-java-client#239]
I am using zendesk-java-client version 0.6.1 jar from the maven repository. The program does not terminate even after performing the close() method. The isClosed() method returns true, but the program does not terminate.  Is this intentional? Is there a work around? Thank you.

**Comment by johnou** [comment]
Fixed with https://github.com/cloudbees/zendesk-java-client/pull/238

**Comment by johnou** [comment]
@aheritier should we release 0.6.2?

**Comment by aheritier** [comment]
yes let's go @johnou

**Comment by aheritier** [comment]
0.6.2 released ~1h ago (waiting for central sync now) @johnou

**Comment by ujjwalsubedi** [comment]
Thank you
