### ISSUE TITLE
IllegalArgumentException: Can not deserialize instance of java.lang.String[] out of VALUE_STRING token

### ISSUE THREAD

**Issue by aditisen** [cloudbees/zendesk-java-client#247]
When trying to get a ticket by externalId, Iterable<Ticket> at 358 in Zendesk.java throws following exception at the complete method at line 2184 in Zendesk.java:

java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Can not deserialize instance of java.lang.String[] out of VALUE_STRING token
 at [Source: N/A; line: -1, column: -1] (through reference chain: org.zendesk.client.v2.model.Ticket["custom_fields"]->org.zendesk.client.v2.model.CustomFieldValue["value"])

**Comment by duemir** [comment]
@aditisen what is the library version that you are using? There were some significant changes to custom fields handling in version 0.6.x

**Comment by aditisen** [comment]
0.6.2  latest version.

**Comment by aditisen** [comment]
I found the issue. It needs jackson 2.7 & up to work. Once I upgraded jackson to 2.8.8, it worked.
