### ISSUE TITLE
permanently delete user

### ISSUE THREAD

**Issue by rodislav** [cloudbees/zendesk-java-client#256]
Hello, it would be nice to have the function to permanently delete a user implemented in the client.

Next to
```
public void deleteUser(long id) {
    complete(submit(req("DELETE", tmpl("/users/{id}.json").set("id", id)), handleStatus()));
}
```

We could add
```
public void deleteUserPermanently(long id) {
    complete(submit(req("DELETE", tmpl("/deleted_users/{id}.json").set("id", id)), handleStatus()));
}
```
https://developer.zendesk.com/rest_api/docs/core/users#permanently-delete-user

**Comment by duemir** [comment]
For reference. #257 adds permanent user delete in among other API.
