### ISSUE TITLE
Please update async-http-client to 1.9.x

### ISSUE THREAD

**Issue by rpk** [cloudbees/zendesk-java-client#26]
Hello, we have another dependency that requires async-http-client 1.9.x.  It would be great if zendesk-java-client could update to 1.9.x, there are only a few breaking interface changes that impact zendesk-java-client. 
```xml
    <dependency>
      <groupId>com.ning</groupId>
      <artifactId>async-http-client</artifactId>
      <version>1.7.12</version>
    </dependency>
```
1.9.3 is the latest version.

Thanks!

**Comment by johnou** [comment]
Work in progress here https://github.com/cloudbees/zendesk-java-client/pull/41.
