### ISSUE TITLE
CodeShip doesn't seem to run the Smoke Tests

### ISSUE THREAD

**Issue by duemir** [cloudbees/zendesk-java-client#279]
**Describe the bug**
RealSmokeTest has more than 20 tests yet Codship build reports

```
Running org.zendesk.client.v2.RealSmokeTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.002 sec - in org.zendesk.client.v2.RealSmokeTest
```

**To Reproduce**
Look at any of the builds in https://app.codeship.com/projects/302087

**Expected behavior**
Smoke Tests are executed.

**Comment by aheritier** [comment]
I confirm that we will have to configure this environment to use our sandbox

**Comment by aheritier** [comment]
I reconfigured it but not sure if it will work I cannot launch CodeShip builds on PRs :-(

**Comment by aheritier** [comment]
https://app.codeship.com/projects/302087/builds/42167376?pipeline=2cab6195-3724-4a83-90fc-0f0434a47870
It's now ok (and I have the same error locally)
