### ISSUE TITLE
irrelevant amount tickets in search request

### ISSUE THREAD

**Issue by asafronienkov** [cloudbees/zendesk-java-client#280]
Search tickets request does not return tickets that were just created.
about 30 seconds after creation a new ticket will be shown in the request below
/api/v2/search.json?query=type:ticket requester:555&sort_by=created_at&sort_order=desc&page=1&per_page=5

**Comment by aheritier** [comment]
https://support.zendesk.com/hc/en-us/articles/203663226-Zendesk-Support-search-reference#topic_qhr_wsc_3v

> **How soon can new data be searched?**
> When you add new data to Zendesk Support, it typically takes about a minute before it's indexed and can be searched.

It looks to be normal.
