### ISSUE TITLE
Ticket comment id

### ISSUE THREAD

**Issue by tkolsen** [cloudbees/zendesk-java-client#281]
Is it possible to get the id of a created comment when using createComment method?

**Comment by aheritier** [comment]
Hi @tkolsen 

  No it's not possible. The creation of the comment is done by creating or updating a ticket. These operations are returning a ticket and not its comments.

https://developer.zendesk.com/rest_api/docs/support/ticket_comments#create-ticket-comment

Regards

**Comment by tkolsen** [comment]
We solved this by getting the comment from the audit events.
