### ISSUE TITLE
Found a bug in organisation/{id}/getusers

### ISSUE THREAD

**Issue by larsbard** [cloudbees/zendesk-java-client#33]
In the code, the url is wrong in the function:  
public Iterable<User> getOrganizationUsers(long id) {
        return new PagedIterable<User>(tmpl("/organization/{id}/users.json").set("id", id),
                handleList(User.class, "users"));
    }

I changed "organization" with "organization**s**" locally, and got the expected response.

**Comment by johnou** [comment]
@larsbard thanks for the report, fixed in the next build.
