### ISSUE TITLE
Dependency org.asynchttpclient:async-http-client@2.10.4 exposes user to vulnerability risk in io.netty:netty-codec-http@4.1.42.Final

### ISSUE THREAD

**Issue by usulkies** [cloudbees/zendesk-java-client#344]
The version 2.10.4 used for dependency org.asynchttpclient:async-http-client transitively imports dependency io.netty:netty-codec-http in version 4.1.42 as described here: https://snyk.io/vuln/SNYK-JAVA-IONETTY-543490

The vulnerability is fixed in versions 4.1.44+ which are used by higher versions of org.asynchttpclient:async-http-client.

https://github.com/cloudbees/zendesk-java-client/blob/86b4334f1900369dadae4291d312efbd22927ec4/pom.xml#L117

**Comment by aheritier** [comment]
ok @usulkies I will have a look at it. thanks

**Comment by usulkies** [comment]
@aheritier Any estimation (What is the process required to bump one version?)

**Comment by aheritier** [comment]
I will release it today @usulkies

**Comment by aheritier** [comment]
done.
