### ISSUE TITLE
How about subclassing ZendeskResponseException for cases like Rate Limiting

### ISSUE THREAD

**Issue by gvh1234** [cloudbees/zendesk-java-client#43]
I'm looking to subclass ZendeskResponseException to specially capture the 429 Rate Limiting error. That error returns useful information including the time to wait before trying again. So my plan is to simply grep through the Response and add a few extra fields on the exception.

Not a problem so far but I'm having trouble writing a small unit test that will trigger a 429 from a sandbox instance. Any ideas on how to provoke one are welcome.
https://support.zendesk.com/hc/en-us/articles/203691336-Best-practices-for-avoiding-rate-limiting

(on the subject of our rate limit problems - we already have ehcache and are now actively trying to refine our cache usage but it's tough when you can't easily capture and respond to this particular error. Then I'll head towards a network cache)

**Comment by johnou** [comment]
We had an interesting discussion about rate limiting here https://github.com/cloudbees/zendesk-java-client/pull/42 it would be nice to come up with a simple rate limiter without pulling in guava as a dependency, perhaps using something like.. http://blog.nirav.name/2015/02/a-simple-rate-limiter-using-javas.html

**Comment by gvh1234** [comment]
We are now going to deploy a Redis-based network cache to get very smart on reading data (I have a Pull Request open on that). For writing I'm probably going to have to look to a RabbitMQ solution to trickle back Comments on Tickets.

But I still think there's mileage in being able to distinguish the 429 error as it's a key feature of the Zendesk API. I can use it with a queue-based solution to ensure we write back to Zendesk in a safe way.

**Comment by duemir** [comment]
Rate Limit Exception was introduced in #135
