### ISSUE TITLE
Is there going to be a new maven release for getTicketsIncrementally changes?

### ISSUE THREAD

**Issue by spencerpowell** [cloudbees/zendesk-java-client#50]
I'm trying to use the zendesk-java-client for a grails project, but I need the getTicketsIncremetnally() functionality.  I have tried cloning and creating a jar file and using that in my grails project but it has given me a ton of issues and headaches.  Are you guys planning on uploading a new version with the getTicketsIncrementally() functionality to Maven?

**Comment by matthewtckr** [comment]
This was addressed in the 0.3.0 and later releases.

**Comment by duemir** [comment]
As noted above this was resolved in release 0.3.0
