### ISSUE TITLE
Infinite loop when reading tickets returned by "org.zendesk.client.v2.Zendesk#getTicketsIncrementally(java.util.Date)"

### ISSUE THREAD

**Issue by topero** [cloudbees/zendesk-java-client#59]
Hello!
First of all I would like to introduce myself a bit: I am a Java EE developer that is currently working integrating Liferay Portal and Zendesk. I have found this project (thank you for your effort!) and I would like to help as much as I can to improve it.

And now, going to the point, I have noticed that "org.zendesk.client.v2.Zendesk.PagedAsyncListCompletionHandler#setPagedProperties in "org.zendesk.client.v2.Zendesk#handleIncrementalList" is not taking into account what is said at https://developer.zendesk.com/rest_api/docs/core/incremental_export#polling-strategy

Resulting that Zendesk is being queried using the same "next_page" value until Zendesk returns an HTTP 429 error code (Too many requests).

A fix is available at my working copy. I want to make a pull request soon. I hope to do not mess things up (it will be my first PR in GitHub :S)

**Comment by duemir** [comment]
Fixed and should be in the library since v0.3.2
