### ISSUE TITLE
HelpCenter getArticles documentation suggests wrong default value

### ISSUE THREAD

**Issue by matthewtckr** [cloudbees/zendesk-java-client#80]
The `getArticlesFromPage(int page)` method should start with a value of "1", not 0.  Passing a "0" leads to an HTTP 400 error.

https://github.com/cloudbees/zendesk-java-client/blob/master/src/main/java/org/zendesk/client/v2/Zendesk.java#L1214

**Comment by matthewtckr** [comment]
This can be closed if/when PR #81 is accepted.

**Comment by ydubreuil** [comment]
Closing as PR #81 is merged
