### ISSUE TITLE
Identity Object should return Long user id

### ISSUE THREAD

**Issue by matthewtckr** [cloudbees/zendesk-java-client#86]
To maintain consistency with other classes, the [Identity class](https://github.com/cloudbees/zendesk-java-client/blob/zendesk-java-client-0.3.1/src/main/java/org/zendesk/client/v2/model/Identity.java#L63) should return the User ID as Long

**Comment by christ66** [comment]
I believe this is fixed in https://github.com/cloudbees/zendesk-java-client/pull/76.

**Comment by matthewtckr** [comment]
It looks like #76 would need a minor version bump to be committed, as would #92.

**Comment by ydubreuil** [comment]
#76 merged
