### ISSUE TITLE
How to debug this error: HTTP/422: Unprocessable Entity

### ISSUE THREAD

**Issue by mdemin914** [cloudbees/zendesk-java-client#91]
I occasionally get the HTTP/422: Unprocessable Entity error using the client. When I do a curl request, in the response from Zendesk there is a helpful error message. For example, here is one for trying to create a user:

{"error":"RecordInvalid","description":"Record validation errors","details":{"email":[{"description":"Email: scooby@doo.com is already being used by another user","error":"DuplicateValue"}]}}

Is there any way to surface this error using the library? This would be extremely helpful for debugging. Thanks in advance.

**Comment by kflorence** [comment]
+1

**Comment by kflorence** [comment]
@mdemin914 FYI if you enable `DEBUG` level logging, you do get this information.

**Comment by mdemin914** [comment]
Hey, how do I do this?  Is there a config option to specify the debug level.
